
services:
  websocket:
    build:
      context: ../
      dockerfile: ./docker/websocket/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "../code/node:/usr/src/app"
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: alpifgame
      MYSQL_USER: alpifgame
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./db/mysql:/var/lib/mysql"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
